language: python

python:
    - 3.5

install:
    - pip install -r requirements-dev.txt

script: ./bin/test

addons:
  postgresql: "9.6"

env:
  - POSTGRES_USER="postgres" POSTGRESS_PASSWORD="" POSTGRES_HOST="127.0.0.1"

notifications:
    email: false
